name: Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ lowercase(github.repository) }}:dev
          target: development
          cache-to: type=gha,mode=max
          cache-from: type=gha
  test:
    needs: build-dev
    runs-on: ubuntu-latest
    container: ghcr.io/${{ lowercase(github.repository) }}:dev
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run flake8
        run: |
          flake8 .
      -
        name: Run black
        run: |
          black --check .
      -
        name: Run isort
        run: |
          isort --check .
      -
        name: Run mypy
        run: |
          mypy .
      -
        name: Run pytest
        run: |
          pytest -v .
